### ISSUE TITLE
Allow per-product restriction messages

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/EDD-Content-Restriction#24]
Not sure how this plays out...if we should a specific error message for a product, or allow a page to be restricted with a specific message, but we might want to look at adding this, as discussed in #17.

I Could see both sides of this, messages per-product, or messages per restricted content.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by tnorthcutt** [comment]
Just a thought: if messages per-product were added, what would happen if more than one product allows access to a piece of restricted content? Seems like per restricted content messages avoids that issue, assuming the messages are only ever shown in the context of a piece of restricted content.

**Comment by pippinsplugins** [comment]
@tnorthcutt Good point. That will get tricky but I'm sure we can come up with something.

**Comment by pippinsplugins** [comment]
Just got another request for this.

@ghost1227 let's make it happen.

**Comment by ghost1227** [comment]
been a while since I really looked at CR! This should be a fun walk down memory lane... What are we thinking? Per content item? Or Per Product? I can't really tell which you're leaning towards from the discussion...

**Comment by pippinsplugins** [comment]
A textarea under the content restriction options that lets it be set on a particular page.

It's more `per-page message` than `per-product message`.

**Comment by ghost1227** [comment]
For the sake of expediency (and getting 2.2 pushed out) I'm not finishing the helper function I was working on for this issue. I've temporarily coded the support for per-content messages into the current workflow, which isn't optimal... but it does work. I've opened a separate issue on streamlining the message determination process which will be addressed for the next update. This is now ready for testing.

**Comment by SDavisMedia** [comment]
This is working well for me but I think it needs to allow very light HTML. It should probably follow the same approach as the post excerpt. One reason for this is linking to the product that restricts the content, like the default message does.

**Comment by pippinsplugins** [comment]
@ghost1227 could you add support for basic HTML through `wp_kses_post()`?

**Comment by ghost1227** [comment]
@SDavisMedia @pippinsplugins Basic HTML support and rich editing added!

**Comment by SDavisMedia** [comment]
Oh wow lol... that's the whole kitchen sink. I'm not mad at it. Working well on my end. :+1:

**Comment by pippinsplugins** [comment]
:+1:
