### ISSUE TITLE
PHP Warnings when used with Wallet extension

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/EDD-Content-Restriction#27]
When adding funds to a your wallet on the front end, you get these debug notices when landing on the purchase confirmation page:

```
PHP Warning:  Invalid argument supplied for foreach() in /wp-includes/functions.php on line 3207

PHP Warning:  array_unique() expects parameter 1 to be array, boolean given in /wp-content/plugins/edd-content-restriction/includes/functions.php on line 331

PHP Warning:  Invalid argument supplied for foreach() in /wp-content/plugins/edd-content-restriction/includes/functions.php on line 333
```

We're not checking if `$files` is there and an array before running `array_unique` on it, and we're not checking if `$ids` is valid before looping through `foreach`. [Reference](https://github.com/easydigitaldownloads/EDD-Content-Restriction/blob/2.1/includes/functions.php#L330-L340).

**Comment by pippinsplugins** [comment]
@mindctrl Could you go ahead and version bump and deploy 2.1.1?
