### ISSUE TITLE
Multiple Restriction Message doesn't work

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/EDD-Content-Restriction#30]
When multiple items are assigned in the content restriction settings of a page, the single restriction message is displayed instead of the multiple restriction message.

[Reported here](https://secure.helpscout.net/conversation/137288582/20819/). Confirmed locally. I have a fix incoming.

**Comment by pippinsplugins** [comment]
Looks good. @mindctrl merge and deploy at will!
