### ISSUE TITLE
Restrict page to customers with active license key

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/EDD-Content-Restriction#32]
Similar to our (minimal) integration with Recurring Payments, we should add support for requiring that the customer has a valid license key to view the content.

This would allow for better time-based access. Once a license key expires, access would be revoked.

**Comment by ghost1227** [comment]
Would this be better added to SL or CR?

**Comment by pippinsplugins** [comment]
Let's keep it in CR.

**Comment by ghost1227** [comment]
I feel like the method I used here is convoluted, but I honestly can't think of a more streamlined way. Any suggestions @pippinsplugins?

**Comment by pippinsplugins** [comment]
I don't think this should be a site-wide setting. It should be page specific, similar to the option to require an active subscription.

**Comment by ghost1227** [comment]
Well... ok! (Don't remember how we did active subscriptions anymore, gotta look it up again)

**Comment by pippinsplugins** [comment]
Activate Recurring Payments and the option will show up in the content restriction metabox.

**Comment by ghost1227** [comment]
I meant code wise 😛 Already found it

**Comment by pippinsplugins** [comment]
@ghost1227 any progress on making this product specific?

**Comment by ghost1227** [comment]
@pippinsplugins This is now ready for testing

**Comment by SDavisMedia** [comment]
Unfortunately, I can't get this to work. Once I gain access to the restricted page, I _cannot_ lose access. Here's a recording of how I'm testing: http://quick.as/7k3ns47lb

I've tried to make sure there's no bad data lingering on the customer record. Can't see any reason why it wouldn't work for me but it works for @ghost1227. So we definitely need another tester.

**Comment by pippinsplugins** [comment]
@SDavisMedia I think some of the changes I just requested on the PR may address that.

**Comment by pippinsplugins** [comment]
@ghost1227 sorry but @SDavisMedia is correct. Once a customer has access, that access cannot be revoked by disabling the license. I've just replicated on the latest version of the branch.

**Comment by ghost1227** [comment]
@pippinsplugins I can't replicate.... I've tested both expiring and disabling and both work as expected every single time

**Comment by SDavisMedia** [comment]
All is well here on `issue/32`. :+1:
