### ISSUE TITLE
Looking for a MO file in an incorrect folder

### ISSUE THREAD

**Issue by boluda** [easydigitaldownloads/EDD-Content-Restriction#33]
Hi there. I noticed that the plugin is looking for the MO file at:

wp-content/pluginswp-content/plugins/edd-content-restriction/languages/edd-cr-es_ES.mo	

Notice the missing slat at "pluginswp-content"

![image](https://cloud.githubusercontent.com/assets/4599915/12364548/8df5369c-bbcf-11e5-9e2f-be9290140a24.png)

Sorry if it's not an issue!

**Comment by cklosowski** [comment]
This doesn't seem to be a bug in Content Restriction. When I look at the provided error I see the following:
`wp-content/pluginswp-content/plugins/...` which tells me there is an error somewhere in determining the `WP_CONTENT` constant. When I test this, I have no issues getting the proper path to the localization files.

@boluda do you have custom `WP_CONTENT_DIR` and `WP_PLUGIN_DIR` constants? If so you may want to make sure they are correct, and test this with nothing but EDD and Content restriction active.

**Comment by boluda** [comment]
Hi Chris! That happens only with some EDD plugins, the rest are fine. I'm using Query Monitor, and the others are correctly using the proper folders.

**Comment by pippinsplugins** [comment]
Can you double check your wp-config for any settings there?

**Comment by boluda** [comment]
Hi Pippin!

Done. Nothing. Triple checked. The thing is that only happens with some EDD plugins, but not all of them. Take a look at this screenshot.

http://snag.gy/rRyVE.jpg

As you can see, "edds" misses the /, while "edd-manual-purchases" doesn't. Weird!

BTW, this is a MINOR problem for me, I can just use the other folder. I'm just reporting to improve the plugin, so there is no rush :)

**Comment by pippinsplugins** [comment]
That's incredibly weird . . . .

**Comment by boluda** [comment]
Yeah, I know. Take a look at this screenshot:

http://snag.gy/eW6qY.jpg

As you can see, with edd-csr there is no problem, but with edd-cr, the path is incorrect. I'm trying to look for any differences on how it's done, but they seem quite the same.

**Comment by boluda** [comment]
Uhmmm... well, in fact there is something. Andrew uses

`$lang_dir = dirname( plugin_basename( __FILE__ ) ) . '/languages/';
`
While you use:

`$lang_dir = EDD_CONTENT_RESTRICTION_DIR . '/languages/';`

EDD_CONTENT_RESTRICTION_DIR being

`define( 'EDD_CONTENT_RESTRICTION_DIR', plugin_dir_path( __FILE__ ) );
`

Both approaches seem to be correct, any thoughts?

**Comment by pippinsplugins** [comment]
Both should work fine . . . can you var_dump() the value of WP_CONTENT_DIR and WP_PLUGINS_DIR?

**Comment by boluda** [comment]
Sure:

WP_CONTENT_DIR  -> string(36) "/usr/home/watomic.com/web/wp-content" 
WP_PLUGINS_DIR  -> string(14) "WP_PLUGINS_DIR"

**Comment by boluda** [comment]
Sure:

string(49) "/usr/home/0YhWOD6Pr3f1/watomic.com/web/wp-content" 
string(57) "/usr/home/0YhWOD6Pr3f1/watomic.com/web/wp-content/plugins"

**Comment by pippinsplugins** [comment]
And what does `EDD_CONTENT_RESTRICTION_DIR` show?

**Comment by boluda** [comment]
Hi again!

string(82) "/usr/home/0YhWOD6Pr3f1/watomic.com/web/wp-content/plugins/edd-content-restriction/"

**Comment by pippinsplugins** [comment]
None of this makes sense. All of those paths are correct and would result in the properly file location.

What if EDD CR and EDD core are the only plugins active?

**Comment by boluda** [comment]
Ok, let me check that!
