### ISSUE TITLE
CR UI on CCF Admin

### ISSUE THREAD

**Issue by topher1kenobe** [easydigitaldownloads/EDD-Content-Restriction#36]
When Custom Checkout Fields 2 and CR are both active, CR UI visible on CCF UI.
![selection_071](https://cloud.githubusercontent.com/assets/341412/13123546/a3ee4248-d58a-11e5-9999-214e584f698d.png)

**Comment by chriscct7** [comment]
It's also on FES

**Comment by pippinsplugins** [comment]
@mindctrl Looks good. Can you deploy this update please?
