### ISSUE TITLE
Compatibility with EDD Bookings 2

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/EDD-Content-Restriction#41]
"Schedules" in EDD Bookings 2.0 should probably not have the content restriction metabox. 

<img width="1252" alt="screen shot 2016-04-20 at 4 58 49 pm" src="https://cloud.githubusercontent.com/assets/1638128/14691627/400ba8fc-0720-11e6-9f70-8b05a7db4eac.png">

**Comment by mintplugins** [comment]
@mindctrl mentioned a smarter way to do this might be to only allow public post types by default for Content Restriction - rather than targeting every new post type that might come along in the future.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
@ghost1227 can you confirm this is fixed with #51?

**Comment by ghost1227** [comment]
I used both Bookings and the Media pages to test during writing. This fixes both.

**Comment by pippinsplugins** [comment]
:+1:
