### ISSUE TITLE
Put settings on sub settings page.

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/EDD-Content-Restriction#43]
Move all Content Restriction settings from the "Extensions" > Main" tab to "Extensions" > "Content Restriction" tab.

**Comment by pippinsplugins** [comment]
@mintplugins Up for tackling this next week?

**Comment by mintplugins** [comment]
@pippinsplugins For sure!

**Comment by ghost1227** [comment]
This has been fixed in the [release/2.2](https://github.com/easydigitaldownloads/EDD-Content-Restriction/tree/release/2.2) branch.
