### ISSUE TITLE
Allow restricted messages to be filtered

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/EDD-Content-Restriction#44]
If a customer views content restricted by a recurring product that is now expired, they will see "This content is restricted to buyers.".

The site owner has no control over that message as it is hard coded. This should likely use the "edd_cr_get_single_restriction_message" and "edd_cr_get_any_restriction_message" like the ones above do:

https://github.com/easydigitaldownloads/EDD-Content-Restriction/blob/master/includes/functions.php#L129

**Comment by ghost1227** [comment]
I've added a filter that allows us to edit the message. Now we've got to close out https://github.com/easydigitaldownloads/edd-recurring/issues/512 to resolve this issue.

**Comment by pippinsplugins** [comment]
@ghost1227 see my comment on the RP repo.

**Comment by ghost1227** [comment]
Replied....

**Comment by pippinsplugins** [comment]
Works great.

**Comment by pippinsplugins** [comment]
Updated issue title to properly reflect the real change made here.
