### ISSUE TITLE
If saving more than 2 restriction parents with variation, 3rd variation un-saved.

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/EDD-Content-Restriction#45]
If you are setting the Content Restriction parents and choosing variations, if you set up more than 2, the 3rd one fails to save the variation correctly:

![3rd-variation-fail](https://cloud.githubusercontent.com/assets/1638128/18550514/45f08488-7b22-11e6-8cd2-14bed06742b1.png)

**Comment by ghost1227** [comment]
@pippinsplugins patch against master or are we going to add a 2.1.5 release branch?

**Comment by pippinsplugins** [comment]
`master` please.

**Comment by ghost1227** [comment]
This actually appears to affect 2+, not 3+

**Comment by ghost1227** [comment]
@pippinsplugins ^

**Comment by ghost1227** [comment]
@pippinsplugins I've tested a fix locally by adding `$( this ).attr( 'data-key', key );` to the `admin-scripts.js` file in EDD core on line 69. In my tests, that fixes all issues brought up in this ticket. Since the fix is in core and not CR itself, where do you want me to submit it? Does it belong in `master`?

**Comment by ghost1227** [comment]
This is fixed once https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4953 is merged.

**Comment by ghost1227** [comment]
Just for sanity sake, the `Has PR` tag is only semi-accurate. The PR is actually in EDD Core, referenced in my previous comment.

**Comment by SDavisMedia** [comment]
I've replicated the original issue here on EDD `master`. EDD `issue/4953` fixes it for me. :+1:

**Comment by pippinsplugins** [comment]
Closing as fixed since it was fixed in core.
