### ISSUE TITLE
Pages display broken on receipt

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/EDD-Content-Restriction#47]
Discovered this while testing another issue.

![screen shot 2016-09-19 at 12 37 38 pm](https://cloud.githubusercontent.com/assets/36433/18642467/6147b00c-7e66-11e6-8412-fbeab285ff8b.PNG)

**Comment by ghost1227** [comment]
Note that this bug only happens if another plugin is already editing the receipt. However, it exists because the method we used to add pages to the receipt is horrible.

**Comment by ghost1227** [comment]
@pippinsplugins I've fixed the current code to work correctly, but the Pages section looks a little derpy... any thoughts on how we can improve this so it's not so out of place?

![screen shot 2016-09-19 at 1 15 42 pm](https://cloud.githubusercontent.com/assets/36433/18643563/51d0050c-7e6b-11e6-81f3-1dcc29bc7863.PNG)

**Comment by ghost1227** [comment]
One thing I’m pondering is making it such that the `edd_cr_get_restricted_pages` function returns pages per product instead of just pages, and adding the pages to the individual product line items instead of in their own single-cell table.

**Comment by pippinsplugins** [comment]
Might be nice to support both options.

**Comment by ghost1227** [comment]
Supporting pages per product would require adding an action to the receipt shortcode in Core. We're severely lacking in flexibility in that shortcode... Basically the only places that are hookable are the end of the main table (where license keys are), after the main table, and after each file in a given download. The actual rows are skipped completely.

**Comment by ghost1227** [comment]
By supporting both, you mean adding a select option to choose between separate table and inline in products table?

**Comment by ghost1227** [comment]
I propose adding an action `edd_payment_receipt_after_download` just before the closing `</tr>` tag on line 288 of `shortcode-receipt.php`

**Comment by pippinsplugins** [comment]
>>>By supporting both, you mean adding a select option to choose between separate table and inline in products table?
Yes.

New action sounds fine.

**Comment by ghost1227** [comment]
@pippinsplugins The below screenshot shows both of the two possibilities I've worked out. The table method can be implemented immediately, while the inline method requires merging the patch I've written for https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4956. I'm not sure which one I prefer, or if both should be included. Thoughts?

![screen shot 2016-09-19 at 2 50 59 pm](https://cloud.githubusercontent.com/assets/36433/18646788/c4e5d550-7e78-11e6-9c5f-0d4d5c580787.PNG)

**Comment by ghost1227** [comment]
How it looks with multiple files/downloads:

![screen shot 2016-09-19 at 3 06 12 pm](https://cloud.githubusercontent.com/assets/36433/18647219/a4f58022-7e7a-11e6-85b8-67de8b617e51.PNG)

**Comment by pippinsplugins** [comment]
I think I like that

**Comment by ghost1227** [comment]
After modifying the initial table to display both product and pages instead of just a dumped list of pages, I prefer the standalone Pages table. As @SDavisMedia said, it's more inline with what we do in other plugins.

**Comment by ghost1227** [comment]
@pippinsplugins which one? That screenshot shows two possibilities...

**Comment by ghost1227** [comment]
Me: Which one? Either/or?
@pippinsplugins: Yes
Me: ...

**Comment by pippinsplugins** [comment]
Oh sorry, I missed that.

I thought we were going to keep the existing display option but add an alternative that only shows the pages inline with the products instead of having a `Pages` section. Am I confused?

**Comment by ghost1227** [comment]
After my modification to the standalone pages table, I don't think the inline option is needed any longer. I included it in the screenshot to let you weigh in. My issue with the original table was how awkward it looked to have a single-column list being dumped into the page with no context. Adding the ability to split pages into per-product rows and adding column headers resolved my issue. In my opinion, while the inline option is better than what we had before, it's less in line with what we do in other extensions and potentially introduces its own set of issues. I think I'd rather leave just the modified Pages table.

**Comment by SDavisMedia** [comment]
I'm having issues here and I tried to track it down based on my site data but I can't put a finger on it. Here's what's happening:

![image 2016-09-21 at 3 50 48 pm](https://cloud.githubusercontent.com/assets/2359131/18731830/7a1c5700-8013-11e6-8b09-210cc250c8d1.png)

That's an image file in my media library. I _cannot_ find the connection between that file and my product that restricts the page you see listed there.

What could be causing this?

**Comment by pippinsplugins** [comment]
@SDavisMedia Try this:

1. Delete the row on the product edit screen
2. Add new file
3. Save product

Does that clear it?

**Comment by SDavisMedia** [comment]
@pippinsplugins The product didn't have any files to begin with. However, adding one file, adding two files, and removing one of those two files had no effect on the the photo link showing up. Product files don't appear to be related.

**Comment by pippinsplugins** [comment]
Weird . . . Clean site otherwise? That makes me think a plugin or something is interfering with the `pre_get_posts` action, resulting in the `Pages` query returning unexpected post types.

**Comment by SDavisMedia** [comment]
Fairly clean. It's my main test site but I don't have anything funky going on or an extensive history. I'll deactivate some stuff to see if I can get different behavior.

**Comment by SDavisMedia** [comment]
I can't find any data that would connect that media entry to the Content Restriction product. I've looked all over. And I can't replicate this at all with a new CR product. We might have to ignore my case here. My product came from an older site and was exported/imported. Perhaps that's related.

I'd say this is good to go. :+1:

**Comment by mintplugins** [comment]
I tested here and everything looks good!

<img width="734" alt="screen shot 2016-11-02 at 2 13 11 pm" src="https://cloud.githubusercontent.com/assets/1638128/19941473/9ba46d18-a106-11e6-8ccd-0e68b2cbbacf.png">
