### ISSUE TITLE
Add support for bundles to shortcodes

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/EDD-Content-Restriction#57]
Currently, the content restriction shortcode only recognizes users who purchased an actual product. In other words, if I have a page restricted to users who have purchased 'Product A', and 'Product A' is included in the bundle 'Product B', common sense says that users who purchased 'Product B' have technically purchased 'Product A' and should be allowed access to the restricted content.

Proposal: Add an option to CR letting site owners choose whether to allow people who purchased bundles CONTAINING a product to access restricted content, or whether to require direct purchase of the product itself. Adjust shortcode conditions accordingly.

**Comment by ghost1227** [comment]
RE: https://secure.helpscout.net/conversation/284054848/48075/?folderId=180504

**Comment by ghost1227** [comment]
@pippinsplugins see my comment on the commit please

**Comment by pippinsplugins** [comment]
It's not the most efficient in the world but I'm not seeing a better way to do it.

**Comment by ghost1227** [comment]
At least I'm not the only one...

**Comment by SDavisMedia** [comment]
`issue/57` is working perfectly on my end. Tested a complete page restriction as well as `[edd_restrict]` shortcode.

**Comment by pippinsplugins** [comment]
just one small change on the PR.
