### ISSUE TITLE
Notice: Undefined variable: message ... on some unrestricted pages

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/EDD-Content-Restriction#75]
<img width="1230" alt="screenshot 2017-02-17 08 15 54" src="https://cloud.githubusercontent.com/assets/2359131/23073141/640619ba-f4e9-11e6-9139-efb99c7cd253.png">

https://github.com/easydigitaldownloads/EDD-Content-Restriction/blob/master/includes/user-functions.php#L153

**Comment by pippinsplugins** [comment]
@ghost1227 could you please work on this after Commissions 3.3 beta is finished?

**Comment by ghost1227** [comment]
Sure thing!

**Comment by SDavisMedia** [comment]
@ghost1227 reminder ping

**Comment by pippinsplugins** [comment]
Fixed.
